appeal/urls.py
from django.urls import path
from appeal.views.appeal_create import AppealCreateView
from appeal.views.appeal_update import AppealUpdateView
from appeal.views.list import AppealListView
from appeal.views.answer_create import AnswerCreateView
from appeal.views.answer_update import AnswerUpdateView

from django.views.generic import TemplateView

app_name = 'appeal'

urlpatterns = [
    path('create/', AppealCreateView.as_view(), name='appeal_create'),
    # path('update/<int:pk>/', AppealUpdateView.as_view(), name='appeal_update'),
    path('list/', AppealListView.as_view(), name='appeal_list'),
    path('answer/<int:pk>/create/', AnswerCreateView.as_view(), name='answer_create'),
    path('answer/<int:pk>/update/', AnswerUpdateView.as_view(), name='answer_update'),

    


]

application/urls.py
from django.urls import path
from application.views.view_application import ApplicationCreateView
from application.views.application_success import ApplicationSuccessView
from application.views.applications_list import ApplicationListView
from application.views.application_detail import ApplicationDetailView, ApplicationByUserView
from application.views.edit_application import ApplicationUpdateView
from application.views.excel_export import export_students_excel

app_name = 'application'

urlpatterns = [
    path('apply/', ApplicationCreateView.as_view(), name='create'),
    path('apply/success/', ApplicationSuccessView.as_view(), name='success'),
    path('list/', ApplicationListView.as_view(), name='list'),
    path("<int:pk>/", ApplicationDetailView.as_view(), name="detail"),
    path('applications/<int:pk>/edit/', ApplicationUpdateView.as_view(), name='edit'),
    path('export-students-excel/', export_students_excel, name='export_students_excel'),
    path('by-user/<int:user_id>/', ApplicationByUserView.as_view(), name='by_user'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('student/', include('student.urls')),
    path('application/', include('application.urls')),
    path('employee/', include('employee.urls')),
    path('appeal/', include('appeal.urls', namespace='appeal')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

main/urls.py
from django.urls import path
from main.views import (
    view_home, logout
    )

app_name = "main"

urlpatterns = [
    path('', view_home.index, name='index'),
    path('logout/', logout.logout_view, name='logout'),
]

users/urls.py
from django.urls import path
from .views import custom_login_view


app_name = 'users'

urlpatterns = [
    path('login/', custom_login_view, name='login'),
]

templates/result/base_page.html
{% load static %}
<!DOCTYPE html><html lang="en"><head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>{% block title %}GFU. GRAND{% endblock %}</title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href="https://files.uzgeouniver.uz/media/files/tg_image_3682980900.png" rel="icon">
  <link href="{% static 'proj/images/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'proj/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'proj/css/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'proj/css/aos.css' %}" rel="stylesheet">
  <link href="{% static 'proj/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'proj/css/swiper-bundle.min.css' %}" rel="stylesheet">

  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'proj/css/main.css' %}" rel="stylesheet">

  <style>
    .btn-get-started {
        background-color: #4DC680;
        margin: 5px;
        display: inline-block;
        color: white;
        padding: 8px 20px;
        border: none;
        border-radius: 10px;
        text-decoration: none;
    }
    .my-btn-color {
      display: inline-block;
      border-radius: 15px;
      padding: 5px 15px;
      color: #4DC680;
      border: 1px solid #4DC680;
    }

    .my-btn-color:hover {
      background-color: #4DC680;
      color: white;
    }
    .my-text {
      color: black;
    }
    .my-text:hover {
      color: #4DC680;
    }
    @keyframes scroll-left {
      0% { transform: translateX(100%); }
      100% { transform: translateX(-100%); }
    }
    .test-banner {
      position: fixed;
      top: 0;
      width: 100%;
      background-color:rgb(220, 244, 232);
      color: red;
      font-weight: bold;
      overflow: hidden;
      height: 2.5rem;
      z-index: 1050;
    }
    .scrolling-text {
      display: inline-block;
      white-space: nowrap;
      padding-left: 30%;
      animation: scroll-left 20s linear infinite;
      font-size: 1rem;
      line-height: 2.5rem;
    }
  </style>


</head>

<body class="index-page d-flex flex-column min-vh-100">
  <header id="header" class="header d-flex align-items-center sticky-top">
    <div class="test-banner mb-5">
      <div class="scrolling-text">Sayt test rejimida ishlamoqda. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;—&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sayt test rejimida ishlamoqda.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; —  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sayt test rejimida ishlamoqda.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;—&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sayt test rejimida ishlamoqda.</div>
    </div>
    <div class="container-fluid container-xl position-relative d-flex align-items-center mt-4">

      <a href="{% url 'main:index' %}" class="logo d-flex align-items-center me-auto">
        <h1 class="sitename text-warning">GRAND</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'main:index' %}" class="active">Bosh sahifa</a></li>
          <li><a href="{% url 'main:index' %}#about">Ma'lumotlar</a></li>
          <li><a href="{% url 'main:index' %}#contact">Aloqa</a></li>

          {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'appeal:appeal_list' %}">Apellyatsiya</a>
            </li>
            {% if request.user.role == 'student' %}
              <li>
                <a href="{% url 'application:list' %}">Arizalar</a>
              </li>
              <li>
                <a href="{% url 'application:list' %}">{{request.user.full_name}}</a>
              </li>
              <li>
                <a class="dropdown-item center" href="#">
                  <form method="post" action="{% url 'main:logout' %}">
                      {% csrf_token %}
                      <button type="submit" class='btn btn-outline-link'><i class="bi bi-arrow-bar-left fs-6"></i> Chiqish</button>
                  </form>
                </a>
              </li>
            {% else %}
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
                    data-bs-toggle="dropdown" aria-expanded="false">
                    {{request.user.full_name}}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% comment %} <li><a class="dropdown-item" href="#">Profil</a></li> {% endcomment %}
                    <li><a class="dropdown-item" href="{% url 'application:list' %}">Arizalar</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li>
                      <a class="dropdown-item center" href="#">
                        <form method="post" action="{% url 'main:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class='btn btn-outline-link'><i class="bi bi-arrow-bar-left fs-6"></i> Chiqish</button>
                        </form>
                      </a>
                    </li>
                  </ul>
              </li>

            {% endif %}



          {% else %}
          <a class="btn-getstarted" href="{% url 'users:login' %}">Kirish</a>
          {% endif %}

        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>
    </div>
  </header>



  <main class="flex-fill">
    {% if messages %}
      <div aria-live="polite" aria-atomic="true" class="position-relative">
        <div class="toast-container position-fixed bottom-0 end-0 p-4 m-5" style="z-index: 1055;">
          {% for message in messages %}
              {% if message.tags != 'error' %}
                <div class="toast align-items-center text-white bg-{{ message.tags }} border-0 fade"
                    role="alert" aria-live="assertive" aria-atomic="true"
                    data-bs-delay="3000" data-bs-autohide="true">
                  <div class="d-flex">
                    <div class="toast-body mt-1 mb-1">
                      {{ message }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                  </div>
                </div>
              {% else %}
                <div class="toast align-items-center text-white bg-danger border-0 fade"
                    role="alert" aria-live="assertive" aria-atomic="true"
                    data-bs-delay="3000" data-bs-autohide="true">
                  <div class="d-flex">
                    <div class="toast-body mt-1 mb-1">
                      {{ message }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                  </div>
                </div>
              {% endif %}
          {% endfor %}
        </div>
      </div>
      <script>
        document.addEventListener("DOMContentLoaded", function () {
          const toastElList = [].slice.call(document.querySelectorAll('.toast'))
          toastElList.forEach(function (toastEl) {
            const toast = new bootstrap.Toast(toastEl)
            toast.show()
          })
        });
      </script>
    {% endif %}


    {% block content %}
    {% endblock %}
  </main>

  
  <footer id="footer" class="footer mt-50">
    
    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="index.html" class="d-flex align-items-center">
            <span class="sitename">GFU</span>
          </a>
          <div class="footer-contact pt-3">
            <p><strong>Manzil:</strong> Toshkent sh. Mirzo Ulug'bek tumani, </p>
            <p>Olimlar ko'chasi, 64-uy</p>
            <p class="mt-3"><strong>Telefon raqam:</strong> <span>+998 (71) 209-11-69</span></p>
            <p><strong>Email:</strong> <span>info@uzgeouniver.uz</span></p>
          </div>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Foydali havolalar</h4>
          <ul>
            <li><i class="bi bi-chevron-right"></i> <a href="https://uzgeouniver.uz/uz/">Bizning Universitet</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="https://uzgeouniver.uz/uz/pages/uni-haqida">Biz haqimizda</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="https://uzgeouniver.uz/uz//">Xizmatlar</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="https://uzgeouniver.uz/uz//">Tuzilma</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Interaktiv xizmatlar</h4>
          <ul>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Elektron kutubxona</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="https://murojaat.uzgeouniver.uz/">Virtual qabul</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="https://vacancy.uzgeouniver.uz/uz/">Vakansiyalar</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="https://pf.bimm.uz/">Portfolio</a></li>
          </ul>
        </div>

        <div class="col-lg-4 col-md-12">
          <h4>Bizning ijtimoiy tarmoqlar</h4>
          
          <div class="social-links d-flex">
            <a href="https://www.youtube.com/channel/UCHbNGfH1JzavP51xMmNN_eQ?view_as=subscriber"><i class="bi bi-youtube"></i></a>
            <a href="https://www.facebook.com/geoscience.official"><i class="bi bi-facebook"></i></a>
            <a href="https://www.instagram.com/geologiya_fanlari_universitet/"><i class="bi bi-instagram"></i></a>
            <a href="https://t.me/gfu_rasmiy_kanali"><i class="bi bi-telegram"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">GFU</strong> <span>Raqamli ta'lim texnologiyalari markazi</span></p>
      
  </footer>
  
  <a href="#">

  <!-- Scroll Top -->
  </a><a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'proj/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'proj/js/validate.js' %}"></script>
  <script src="{% static 'proj/js/aos.js' %}"></script>
  <script src="{% static 'proj/js/glightbox.min.js' %}"></script>
  <script src="{% static 'proj/js/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'proj/js/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'proj/js/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'proj/js/swiper-bundle.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'proj/js/main.js' %}"></script>
  <!-- Bootstrap JS (CDN) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>


</body></html>

templates/result/index.html
{% extends 'result/base_page.html' %}
{% load static %}
{% block content %}
    <section id="hero" class="hero section">

      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center" data-aos="fade-up">
            <h1>Ta’lim grantlarini qayta taqsimlash uchun platforma.</h1>
            <p>Hemis orqali kirib grant uchun ariza topshiring!</p>
            <div class="d-flex">
              {% if request.user.role == 'training' or request.user.role == 'spirituality' or request.user.role == 'special' %}
                  <a href="{% url "application:list" %}" class="ms-1 btn-get-started">Arizalar</a>
              {% elif request.user.role == 'student' %}
                  <a href="{% url "application:create" %}" class="ms-1 btn-get-started">Ariza yuborish</a>
              {% else %}
                  <a href="{% url 'login_with_hemis' %}" class="btn-get-started">Hemis orqali kirish</a>
              {% endif %}
              <a href="https://www.youtube.com/watch?v=dmy9i7GcbTE" class="glightbox btn-watch-video d-flex align-items-center"><i class="bi bi-play-circle"></i><span>Qo'lanma</span></a>
            </div>
            
          </div>
          <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-out" data-aos-delay="100">
            <img src="{% static 'proj/images/hero-img.png' %}" class="img-fluid animated" alt="">
          </div>
        </div>
      </div>

    </section><!-- /Hero Section -->

    <section id="stats" class="stats section">

      <div class="container" data-aos="fade-up" data-aos-delay="10">

        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="stats-item text-center w-100 h-100">
              <span data-purecounter-start="0" data-purecounter-end="{{students_count}}" data-purecounter-duration="1" class="purecounter"></span>
              <p>Universitet talabalar</p>
            </div>
          </div><!-- End Stats Item -->

          <div class="col-lg-3 col-md-6">
            <div class="stats-item text-center w-100 h-100">
              <span data-purecounter-start="0" data-purecounter-end="{{applications_count}}" data-purecounter-duration="1" class="purecounter"></span>
              <p>Kelib tushgan arizalar</p>
            </div>
          </div><!-- End Stats Item -->

          <div class="col-lg-3 col-md-6">
            <div class="stats-item text-center w-100 h-100">
              <span data-purecounter-start="0" data-purecounter-end="{{approved_applications}}" data-purecounter-duration="1" class="purecounter"></span>
              <p>Tasdiqlangan arizalar</p>
            </div>
          </div><!-- End Stats Item -->

          <div class="col-lg-3 col-md-6">
            <div class="stats-item text-center w-100 h-100">
              <span data-purecounter-start="0" data-purecounter-end="{{rejected_applications}}" data-purecounter-duration="1" class="purecounter"></span>
              <p>Rad etilgan arizalar</p>
            </div>
          </div><!-- End Stats Item -->

        </div>

      </div>

    </section><!-- /Stats Section -->


    <!-- About Section -->
    <section id="about" class="about section">

      <!-- Section Title -->
      <div class="container section-title" data-aos="fade-up">
        <span>Ma'lumotlar<br></span>
        <h2>Ma'lumotlar</h2>
        <p>Grant uchun ariza topshirish shartlari va qo'llanma.</p>
      </div><!-- End Section Title -->

      <div class="container">

        <div class="row gy-4">
          <div class="col-lg-6 position-relative align-self-start" data-aos="fade-up" data-aos-delay="100">
            <img src="{% static 'proj/images/about.png' %}" class="img-fluid" alt="">
            <a href="https://www.youtube.com/watch?v=dmy9i7GcbTE" class="glightbox pulsating-play-btn"></a>
          </div>
          <div class="col-lg-6 content" data-aos="fade-up" data-aos-delay="200">
            <h3>Universitetda talabalarga grantlarni taqdim etish va qayta taqsimlash tartibi to'g'risida </h3>
            <p class="fst-italic">
               Universitet tomonidan tabaqalashtirilgan tarzda 
               Grandlarni qayta taqsimlash uchun ariza topshirishga 
               qo'yilgan talablar:
            </p>
            <ul>
              <li><i class="bi bi-check2-all"></i> <span>O'zbekiston Respublikasi fuqorosi</span></li>
              <li><i class="bi bi-check2-all"></i> <span>GPA ko'rsatkichi 3.5 dan baland bo'lishi</span></li>
              <li><i class="bi bi-check2-all"></i> <span>Ijtimoiy faol talaba</span></li>
            </ul>
            <p>
              Ariza topshirish uchun <a href="{% url 'login_with_hemis' %}">Hemis</a> orqali kirib, ariza qoldiring.
              Qulaylik yaratish maqsadida ariza ma'lumotlaringiz avtomatik ravishda to'ldiriladi.
              Arizangizni yuborganingizdan so'ng, mutaxassislar tomonidan ko'rib chiqiladi. 
              Yakuniy natijalarni <a href="https://uzgeouniver.uz/uz//">Universitetning rasmiy veb-saytida</a> e'lon qilinadi. 
            </p>
          </div>
        </div>

      </div>

    </section><!-- /About Section -->

    

    <!-- Contact Section -->
    <section id="contact" class="contact section">

      <!-- Section Title -->
      <div class="container section-title" data-aos="fade-up">
        <span>Aloqa ma'lumotlari</span>
        <h2>Aloqa </h2>
        <p>Murojaatingizni qoldiring mutahasislarimiz siz bilan aloqaga chiqishadi!</p>
      </div><!-- End Section Title -->

      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="row gy-4">

          <div class="col-lg-6">
            <div class="info-wrap">
              <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="200">
                <i class="bi bi-geo-alt flex-shrink-0"></i>
                <div>
                  <h3>Bizning manzil</h3>
                  <p>Toshkent sh. Mirzo Ulug'bek tumani, Olimlar ko'chasi, 64-uy</p>
                </div>
              </div><!-- End Info Item -->

              <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="300">
                <i class="bi bi-telephone flex-shrink-0"></i>
                <div>
                  <h3>Bizga qo'ng'iroq qiling</h3>
                  <p>+998 (71) 209-11-69</p>
                </div>
              </div><!-- End Info Item -->

              <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="300">
                <i class="bi bi-envelope flex-shrink-0"></i>
                <div>
                  <h3>Pochta</h3>
                  <p>info@uzgeouniver.uz</p>
                </div>
              </div><!-- End Info Item -->

            </div>
          </div>
          <div class="col-lg-6 gy-4">
              <div class="info-wrap">
              
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3382.981656782843!2d69.33783159382342!3d41.34067446325612!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38aef466b1d2a92d%3A0x1fa3714a97987c89!2sGeologiya%20fanlari%20universiteti!5e1!3m2!1suz!2s!4v1747722029027!5m2!1suz!2s" width="580" height="260" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                
              </div>
          </div>
        </div>

      </div>

    </section><!-- /Contact Section --> 

{% endblock %}