appeal/urls.py
from django.urls import path
from appeal.views.appeal_create import AppealCreateView
from appeal.views.appeal_update import AppealUpdateView
from appeal.views.list import AppealListView
from appeal.views.answer_create import AnswerCreateView
from appeal.views.answer_update import AnswerUpdateView

from django.views.generic import TemplateView

app_name = 'appeal'

urlpatterns = [
    path('create/', AppealCreateView.as_view(), name='appeal_create'),
    # path('update/<int:pk>/', AppealUpdateView.as_view(), name='appeal_update'),
    path('list/', AppealListView.as_view(), name='appeal_list'),
    path('answer/<int:pk>/create/', AnswerCreateView.as_view(), name='answer_create'),
    path('answer/<int:pk>/update/', AnswerUpdateView.as_view(), name='answer_update'),

    


]

application/urls.py
from django.urls import path
from application.views.view_application import ApplicationCreateView
from application.views.application_success import ApplicationSuccessView
from application.views.applications_list import ApplicationListView
from application.views.application_detail import ApplicationDetailView, ApplicationByUserView
from application.views.edit_application import ApplicationUpdateView
from application.views.excel_export import export_students_excel

app_name = 'application'

urlpatterns = [
    path('apply/', ApplicationCreateView.as_view(), name='create'),
    path('apply/success/', ApplicationSuccessView.as_view(), name='success'),
    path('list/', ApplicationListView.as_view(), name='list'),
    path("<int:pk>/", ApplicationDetailView.as_view(), name="detail"),
    path('applications/<int:pk>/edit/', ApplicationUpdateView.as_view(), name='edit'),
    path('export-students-excel/', export_students_excel, name='export_students_excel'),
    path('by-user/<int:user_id>/', ApplicationByUserView.as_view(), name='by_user'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('student/', include('student.urls')),
    path('application/', include('application.urls')),
    path('employee/', include('employee.urls')),
    path('appeal/', include('appeal.urls', namespace='appeal')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

application/forms/ball_forms.py
from application.models import BallApplication, SpiritualityBall, TrainingBall, Application
from django import forms


class SpiritualityBallForm(forms.ModelForm):
    class Meta:
        model = SpiritualityBall
        fields = ['field1', 'field2', 'field3', 'field4', 'field5',
                  'field6', 'field7', 'field8', 'field9', 'field10', 'field11']
 

class TrainingBallForm(forms.ModelForm):
    class Meta:
        model = TrainingBall
        fields = ['field']
        
    
class SpecialForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['application_status']
        widgets = {
            'application_status': forms.Select(attrs={'class': 'form-select'})
        }
        labels = {
            'application_status': 'Ariza holati'
        }

application/forms/create_application.py
# Hemis bilan foydalangan xolatda
from django import forms
from application.models import Application
from student.models import Student
from users.models import User
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import UploadedFile

# Telefon raqami validatori
phone_regex = RegexValidator(
    regex=r'^\+?998\d{9}$',
    message="Telefon raqami +998901234567 formatida bo'lishi kerak."
)

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = [
                'reading_culture', 
                'five_initiatives', 
                'manners', 
                'participation_in_events', 
                'attendance', 
                'enlightenment_classes', 
                'volunteer_work', 
                'cultural_visits', 
                'sports_activity', 
                'spiritual_enlightenment'
            ]

        widgets = {
            field: forms.FileInput(attrs={'class': 'form-control'})
            for field in fields
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def clean(self):
        cleaned_data = super().clean()
        for field in self.Meta.fields:
            file = cleaned_data.get(field)
            if isinstance(file, UploadedFile):  # Faqat yangi yuklangan fayllarni tekshir
                if file.content_type != 'application/pdf':
                    self.add_error(field, "Faqat PDF formatdagi fayl yuklash mumkin.")
                if file.size > 10 * 1024 * 1024:
                    self.add_error(field, "Fayl hajmi 10 MB dan oshmasligi kerak.")
        return cleaned_data

appeal/views/list.py
from django.views.generic import ListView
from django.shortcuts import redirect
from appeal.models import Appeal
from users.models import User

class AppealListView(ListView):
    model = Appeal
    template_name = 'appeal/list.html'
    context_object_name = 'appeals'

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            if user.role == 'student':
                # Student faqat o'z apelatsiyalarini ko'radi
                return Appeal.objects.filter(student__user=user)
            elif user.role == 'training' or user.role == 'spirituality' or user.role == 'special':
                # Expert barcha apelatsiyalarni ko'radi
                return Appeal.objects.all()
        return Appeal.objects.none()

application/views.py
from django.shortcuts import render

application/views/application_detail.py
from django.views import View
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from datetime import datetime
from application.models import BallApplication
from application.forms.ball_forms import SpiritualityBallForm, TrainingBallForm, SpecialForm

class ApplicationDetailView(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            from django.contrib.auth.views import redirect_to_login
            return redirect_to_login(request.get_full_path())
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        user = request.user
        ball = get_object_or_404(BallApplication, pk=pk)

        # Faqat student o'zining arizasini ko'rishi mumkin
        if user.role == 'student' and ball.application.student != user.profile:
            messages.info(request, "Sizga ruxsat berilmagan!")
            return redirect('main:index')

        form = None
        selected_status = None
        choices = None

        if user.role == 'training':
            if ball.ball_training:
                form = TrainingBallForm(instance=ball.ball_training)
            else:
                form = TrainingBallForm(initial={'field': ball.application.student.gpa * 16})

        elif user.role == 'spirituality':
            if ball.ball_spirituality:
                form = SpiritualityBallForm(instance=ball.ball_spirituality)
            else:
                form = SpiritualityBallForm(initial={'field3': ball.application.student.gpa * 2})

        elif user.role == 'special':
            app_obj = ball.application
            form = SpecialForm(instance=app_obj)
            selected_status = app_obj.application_status
            choices = form.fields['application_status'].choices

        return render(request, 'application/detail.html', {
            'application': ball,
            'form': form,
            'selected_status': selected_status,
            'choices': choices,
        })

    def post(self, request, pk):
        user = request.user
        ball = get_object_or_404(BallApplication, pk=pk)

        if user.role == 'training':
            form = TrainingBallForm(request.POST)
            if form.is_valid():
                training_instance = form.save()
                ball.ball_training = training_instance
                ball.save()
                messages.success(request, "Arizaga ball muvofaqiyatli qo'yildi!")
                return redirect('application:list')

        elif user.role == 'spirituality':
            form = SpiritualityBallForm(request.POST)
            if form.is_valid():
                spirituality_instance = form.save()
                ball.ball_spirituality = spirituality_instance
                ball.save()
                messages.success(request, "Arizaga ball muvofaqiyatli qo'yildi!")
                return redirect('application:list')

        if user.role == 'special':
            form = SpecialForm(request.POST, instance=ball.application)
            if form.is_valid():
                form.save()
                messages.success(request, "Maxsus holat saqlandi.")
                return redirect('application:list')
            else:
                selected_status = form.data.get('application_status')
                choices = form.fields['application_status'].choices
                return render(request, 'application/detail.html', {
                    'application': ball,
                    'form': form,
                    'selected_status': selected_status,
                    'choices': choices,
                })

        # Agar valid bo'lmasa
        return render(request, 'application/detail.html', {
            'application': ball,
            'form': form
        })




class ApplicationByUserView(View):
    def get(self, request, user_id):
        current_year = datetime.now().year
        try:
            # Arizani topamiz
            ball = BallApplication.objects.get(
                application__student__user__id=user_id,
                application__created_at__year=current_year
            )
            # Tayyor viewga redirect qilamiz
            return redirect(reverse('application:detail', kwargs={'pk': ball.pk}))
        except BallApplication.DoesNotExist:
            messages.error(request, "Ushbu foydalanuvchining joriy yil uchun arizasi topilmadi.")
            return redirect('main:index')

application/views/application_success.py
from django.views.generic import TemplateView

class ApplicationSuccessView(TemplateView):
    template_name = 'application/success.html'

application/views/applications_list.py
from django.views.generic import ListView
from application.models import BallApplication

class ApplicationListView(ListView):
    model = BallApplication
    template_name = 'application/list.html'
    context_object_name = 'applications' 
    
    def get_queryset(self):
        user = self.request.user
        queryset = BallApplication.objects.all()
        training_filter = self.request.GET.get('training', None)
        spirituality_filter = self.request.GET.get('ball_spirituality', None)
        status_filter = self.request.GET.get('application_status', None)

        if user.role == 'student':
            return queryset.filter(application__student=user.profile)

        if user.role == 'training':
            if training_filter == 'exists':
                queryset = queryset.filter(ball_training__isnull=False)
            elif training_filter == 'none':
                queryset = queryset.filter(ball_training__isnull=True)
            return queryset
        
        elif user.role == 'spirituality':
            if spirituality_filter == 'exists':
                queryset = queryset.filter(ball_spirituality__isnull=False)
            elif spirituality_filter == 'none':
                queryset = queryset.filter(ball_spirituality__isnull=True)
            return queryset

        elif user.role == 'special':
            if status_filter:
                queryset = queryset.filter(application__application_status=status_filter)

            return queryset.filter(ball_spirituality__isnull=False,  ball_training__isnull=False)
        
        return BallApplication.objects.none()
    
        


        
        

application/views/edit_application.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from application.models import Application
from application.forms.create_application import ApplicationForm 
from application.services.validation import ApplicationValidationService
from application.services.validation import CombinedValidationService, UserValidationService

class ApplicationUpdateView(View):

    validation_service = CombinedValidationService()

    def get(self, request, pk):
        try:
            self.validation_service.validate(request)
        except Exception as e:
            messages.error(request, str(e))
            return redirect('main:index')
        
        application = get_object_or_404(Application, pk=pk, student__user=request.user)


        form = ApplicationForm(instance=application)
        return render(request, 'application/edit.html', {'form': form, 'application': application})

    def post(self, request, pk):
        try:
            self.validation_service.validate(request)
        except Exception as e:
            messages.error(request, str(e))
            return redirect('main:index')
        
        application = get_object_or_404(Application, pk=pk, student__user=request.user)

        form = ApplicationForm(request.POST, request.FILES, instance=application)
        if form.is_valid():
            form.save()
            messages.success(request, "Ariza muvaffaqiyatli yangilandi.")
            return redirect('application:list')
        return render(request, 'application/edit.html', {'form': form, 'application': application})

application/views/excel_export.py
from django.shortcuts import redirect
from django.http import HttpResponse
from django.contrib import messages
from application.models import BallApplication
from openpyxl import Workbook

def export_students_excel(request):

    user = request.user

    if not user.is_authenticated or user.role != 'special':
        messages.info(request, "Sizga bunday ruxsat berilmagan!")
        return redirect('application:list')
        
    print("user:", user.role)
    
    wb = Workbook()
    ws = wb.active
    ws.title = "Talabalar"

    # Ustunlar
    ws.append(['Full Name', 'Student ID Number', 'Guruh', 'Passport Number', 
               'GPA', "Ta'lim",'Manaviyat', "Umumiy bal"])

    ball_applications = BallApplication.objects.select_related(
        'application__student__user',
        'ball_training',
        'ball_spirituality'
    ).all()

    for ba in ball_applications:
        student = ba.application.student
        user = student.user

        # Har doim mavjud bo'lishiga ishonch yo‘q, shuning uchun null holatlarni tekshiramiz
        ball_training = ba.ball_training.field if ba.ball_training else ""
        ball_spirituality_total = ba.ball_spirituality.total if ba.ball_spirituality else ""

        ws.append([
            user.full_name,
            student.student_id_number,
            student.group,
            student.passport_number,
            student.gpa,
            ball_training,
            ball_spirituality_total,
            ba.total_ball
        ])

    # HTTP javobga yozish
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=students.xlsx'
    wb.save(response)
    return response

application/views/view_application.py
from django.shortcuts import render, redirect
from django.views import View
from application.forms.create_application import ApplicationForm
from django.contrib import messages
from application.services.create import ApplicationCreationService
from application.services.validation import UserValidationService, CombinedValidationService
from django.contrib.auth.mixins import LoginRequiredMixin

class ApplicationCreateView(LoginRequiredMixin, View):
    
    def dispatch(self, request, *args, **kwargs):
        self.validation_service = CombinedValidationService()
        self.create_application_service = ApplicationCreationService()

        try:
            self.validation_service.validate(request)
        except Exception as e:
            messages.error(request, str(e))
            return redirect('main:index')

        return super().dispatch(request, *args, **kwargs)

    login_url = 'users:login'
    redirect_field_name = 'next'

    def get(self, request):
        application_form = ApplicationForm()
        return render(request, 'application/create.html', {
            'form': application_form,
        })

    def post(self, request):
        form = ApplicationForm(request.POST, request.FILES)
        if not form.is_valid():
            messages.error(request, "Iltimos, formadagi xatolarni tuzating.")
            return render(request, 'application/create.html', {'form': form})
        
        try:
            self.create_application_service.create(request, form)
            messages.success(request, "Ariza muvofaqiyatli yuborildi")
            return redirect('application:list') 
        except Exception as e:
            messages.error(request, str(e))
            return render(request, 'application/create.html', {'form': form})

        
    

application/templates/application/create.html
{% extends 'result/base_page.html' %}
{% load form_tags %}
{% load static %}

{% block title %}Ariza yaratish{% endblock %}

{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-7 col-lg-10">
      <div class="card shadow border-0">
        <div class="card-header text-center rounded-top">
          <h3 class="m-3 text-black fw-bold">Ariza</h3>
        </div>

        <div class="card-body">
          <form method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}

            <!-- Talaba ma'lumotlari (o‘qish uchun) -->
            <h4 class="mb-4 mt-2 text-secondary">Talaba ma'lumotlari</h4>
            <div class="row mb-3">
              <label class="form-label">F.I.SH</label>
              <input type="text" class="form-control" value="{{ request.user.full_name }}" readonly>
            </div>
            <div class="row mb-4">
              <label for="student_id" class="form-label">GPA</label>
              <input type="text" id="student_gpa" name="student_gpa" class="form-control" value="{{ request.user.profile.gpa }}" readonly>
            </div>

            <!-- Qo'llab-quvvatlovchi hujjatlar yuklash -->
            <h4 class="mb-3 text-secondary">Ijtimoiy faollik</h4>
            <p class="text-danger small pb-2">
              Tizm 6 mb gacha bo'lgan pdf formatidagi fayllarni qabul qiladi.
            </p>

            {% for field in form %}
              <div class="mb-4">
                <label for="{{ field.id_for_label }}" class="form-label">
                  {{ field.label }}
                  {% if field.field.required %}<span class="text-danger">*</span>{% endif %}
                </label>

                {{ field|add_class:"form-control" }}

                {% if field.value %}
                  <a href="{{ field.value.url }}" target="_blank">Yuklangan faylni ko‘rish</a>
                {% endif %}

                {% if field.errors %}
                  <div class="text-danger small">
                    {% for error in field.errors %}
                      {{ error }}<br>
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <br/>
            <button type="submit" class="btn btn-success w-100">Yuborish</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

application/templates/application/edit.html
{% extends 'result/base_page.html' %}
{% load form_tags %}
{% load static %}

{% block title %}Arizani tahrirlash{% endblock %}

{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card shadow border-0">
        <div class="card-header text-center rounded-top">
          <h3 class="m-3 text-black fw-bold">Arizani tahrirlash</h3>
            <p class="text-danger small pb-2">
              Tizm 6 mb gacha bo'lgan pdf formatidagi fayllarni qabul qiladi.
            </p>
        </div>

        <div class="card-body">
          <form method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            <input type="hidden" name="_method" value="PUT">

            {% for field in form %}
            <div class="row mb-4 align-items-center">
                
                <!-- Chap ustun: Label (field name with file name if exists) -->
                <div class="col-md-6 text-end pe-4">
                  <label for="{{ field.id_for_label }}" class="form-label fw-semibold mb-0">
                    {% with field_name=field.name %}
                      {% with file_obj=application|attr:field_name %}
                        {% if file_obj %}
                          <a href="{{ file_obj.url }}" target="_blank">
                            {{ field.label }} ({{ file_obj.name|cut:"uploads/" }})
                          </a>
                        {% else %}
                          {{ field.label }}
                        {% endif %}
                      {% endwith %}
                    {% endwith %}
                  </label>
                </div>

                <!-- O‘ng ustun: File input -->
                <div class="col-md-6">
                {{ field|add_class:"form-control" }}

                {% if field.errors %}
                    <div class="text-danger small mt-1">
                    {% for error in field.errors %}
                        {{ error }}<br>
                    {% endfor %}
                    </div>
                {% endif %}
                </div>
            </div>
            {% endfor %}


            <button type="submit" class="btn btn-success w-100">Saqlash</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

application/templates/application/list.html
{% extends 'result/base_page.html' %}
{% load static %}
{% block title %}Arizalar ro'yxati{% endblock %}

{% block content %}
<div class="container m-4">
    <div>
        <h2 class="h2">Arizalar ro'yxati</h2>
        <div class="btn-group my-text" role="group" aria-label="Application status filters">
            {% if request.user.role == "training" %}
            <a href="?training=none"
                class="btn"
                style="
                    border: 1px solid #06b6d4;
                    {% if request.GET.training == 'none' %}
                        background-color: #06b6d4;
                        color: white;
                    {% else %}
                        color: #06b6d4;
                    {% endif %}
                ">
                Yangi kelgan arizalar
            </a>

            <a href="?training=exists"
                class="btn"
                style="
                    border: 1px solid #0f766e;
                    {% if request.GET.training == 'exists' %}
                        background-color: #0f766e;
                        color: white;
                    {% else %}
                        color: #0f766e;
                    {% endif %}
                ">
                Baholangan arizalar
            </a>

            {% elif request.user.role == "spirituality" %}
                <a href="?ball_spirituality=none" 
                    class="btn"
                    style="
                        border: 1px solid #06b6d4;  
                        {% if request.GET.ball_spirituality == 'none' %}
                            background-color: #06b6d4;
                            color: white;
                        {% else %}
                            color: #06b6d4;
                        {% endif %}
                    ">
                    Yangi kelgan arizalar
                </a>

                <a href="?ball_spirituality=exists" 
                    class="btn"
                    style="
                        border: 1px solid #10b981;  /* green-500 */
                        {% if request.GET.ball_spirituality == 'exists' %}
                            background-color: #10b981;
                            color: white;
                        {% else %}
                            color: #10b981;
                        {% endif %}
                    ">
                    Baholangan arizalar
                </a>

            {% elif request.user.role == "special" %}
                <a href="?application_status=new" 
                class="btn"
                style="
                    border: 1px solid #3b82f6;  /* blue-500 */
                    {% if request.GET.application_status == 'new' %}
                        background-color: #3b82f6;
                        color: white;
                    {% else %}
                        color: #3b82f6;
                    {% endif %}
                ">
                Yangi kelgan arizalar
                </a>

                <a href="?application_status=approved" 
                class="btn"
                style="
                    border: 1px solid #10b981;  /* green-500 */
                    {% if request.GET.application_status == 'approved' %}
                        background-color: #10b981;
                        color: white;
                    {% else %}
                        color: #10b981;
                    {% endif %}
                ">
                Tasdiqlangan arizalar
                </a>

                <a href="?application_status=rejected" 
                class="btn"
                style="
                    border: 1px solid #ef4444;  /* red-500 */
                    {% if request.GET.application_status == 'rejected' %}
                        background-color: #ef4444;
                        color: white;
                    {% else %}
                        color: #ef4444;
                    {% endif %}
                ">
                Rad etilgan arizalar
                </a>
            {% endif %}
        </div>
        {% if request.user.role == 'student' %}
            <a href="{% url 'application:create' %}" class="btn btn-primary mb-2 mt-2 float-end">
                <i class="bi bi-plus-circle"></i> Ariza yuborish
            </a>
        {% else %}
            <form method="get" action="{% url 'application:export_students_excel' %}">
                <button type="submit" class="btn btn-success mb-2 mt-2 float-end">
                    <i class="bi bi-file-earmark-excel"></i> Arizalarni yuklab olish
                </button>
            </form>
        {% endif %}
        


        <div class="m-2">
            {% if request.user.role == "spirituality" %}
                <p class="text-success">Ijtimoiy faollikni aniqlash bo'yicha komissiya</p>
            {% elif request.user.role == "training" %}
                <p class="text-primary">Akademik o'zlashtirish ko'rsatkichini aniqlash bo'yicha komissiya</p>
            {% elif request.user.role == "student" %}
                <p class="text-info">Siz yuborgan arizalaringiz:</p>
            {% elif request.user.role == "special" %}
                <p class="text-warning">Maxsus komissiya</p>
            {% endif %}
        </div>
    </div>

    <div class="card-body p-0">
        <table class="table table-bordered table-hover mt-3 mb-5">
            <thead class="thead-light">
                <tr class="text-center">
                    <th>#</th>
                    <th>F.I.Sh</th>
                    {% if request.user.role != 'student' %}
                        <th>Ball</th>
                    {% endif %}
                    <th>Yuborilgan Sana</th>
                    <th>Status</th>
                    <th>Ko'rish</th>
                </tr>
            </thead>
            <tbody class="align-middle">
                {% for app in applications %}
                    <tr>
                        <td class="text-center">{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'application:detail' app.pk %}" class="my-text">{{ app.application.student.user.full_name }}</a> 
                        </td>
                        {% if request.user.role == 'training' %}
                            <td class="text-center">{{ app.ball_training.field }}</td>
                        {% elif request.user.role == 'spirituality' %}
                            <td class="text-center">{{ app.ball_spirituality.total }}</td>
                        {% elif request.user.role == 'special' %}
                            <td class="text-center">Umumiy bal: {{ app.total_ball }}</td>
                        {% endif %}
                        <td class="text-center">{{ app.application.created_at|date:"Y-m-d H:i" }}</td>
                        <td class="text-center text-primary">
                            {% if app.application.application_status == 'approved' %}
                                <img src="{% static 'icons/check.png' %}" style="width: 20px;" alt="Tasdiqlangan"></img>
                            {% elif app.application.application_status == 'rejected' %}
                                <img src="{% static 'icons/cross.png' %}" style="width: 20px;" alt="Rad etilgan"></img>
                            {% else %}
                                {% if request.user.role == 'student' %}
                                    Jarayonda
                                {% else %}
                                    <img src="{% static 'icons/bell.png' %}" style="width: 20px;" alt="Yangi kelgan"></img>
                                {% endif %}
                            {% endif %}
                        </td>
                        <td class="text-center">
                            <a href="{% url 'application:detail' app.pk %}" class="btn btn-sm my-btn-color">Ko'rish</a> 
                            {% if request.user.role == 'student' %}
                                <a href="{% url 'application:edit' app.pk %}" class="btn btn-sm my-btn-color">Tahrirlash</a>
                                <a class="btn btn-sm my-btn-color" href="{% url 'appeal:appeal_create' %}">Apilatsiyaga</a>
                            {% endif %}
                        </td> 
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5" class="text-center p-5">Hozircha hech qanday ariza yo'q.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

application/templates/application/success.html
{% extends 'base.html' %}

{% block title %}Ariza Muvaffaqiyatli Yuborildi{% endblock %}

{% block content %}
    <h2>Rahmat! Arizangiz muvaffaqiyatli yuborildi.</h2>
    <a href="{% url 'application:create' %}">Yana ariza yuborish</a>
{% endblock %}